version: '3.8'
services:

  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - pouetpouet
      
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - pouetpouet

  api:
    container_name: api
    image: gabrieldela/nodejs-example:1.0
    restart: always
    environment:
      PORT: 3000
      DB_HOST: "db"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "mysecretpassword"
      DB_DATABASE: "postgres"
      DB_DAILECT: "postgres"
      DB_PORT: 5432

      ACCESS_TOKEN_SECRET: "DEZ23D3DZ2é46&&1d56éczc3D654&d&3"
      REFRESH_TOKEN_SECRET: "B5é&ééçàààczee6666zau((3D654&d&3"
      ACCESS_TOKEN_EXPIRY: "15m"
      REFRESH_TOKEN_EXPIRY: "7d"
      REFRESH_TOKEN_COOKIE_NAME: "jid"
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - pouetpouet

networks:
  pouetpouet: