apiVersion: v1
kind: Secret
metadata:
  name: api-secret
type: Opaque
data:
  ACCESS_TOKEN_SECRET: dGl5SnUvN0o2RlJCQ0QvUXVEUU41VzVydWljbFBDT21zdmdtZ2svcWxybFZEZURQUTdod3Zzem94SVdTTXE/VQ==
  DB_PASSWORD: bXlzZWNyZXRwYXNzd29yZA==
  DB_USERNAME: cG9zdGdyZXM=
  REFRESH_TOKEN_SECRET: SzRHT2xpUllnTFkxSj15TVItRjU0UlN6WGFYRUhKVmw5YWhaSzlBIWNyP0luRjYhZz1nZGxTMTdHZ0lZLUhsZA==